DATABASE_URL = "mysql://username:password@localhost/database_name"
# Gen oauth client id and client secret for github here
# https://github.com/settings/developers
OAUTH_CLIENT_ID = "some_id"
OAUTH_CLIENT_SECRET = "some_secret"
OAUTH_AUTH_URL = "https://github.com/login/oauth/authorize"
OAUTH_TOKEN_URL = "https://github.com/login/oauth/access_token"