# ############
# # Database #
# ############
# dbtype://username:password@serverip/dbname
DATABASE_URL = "mysql://username:password@localhost/database_name"
# #########
# # Login #
# #########
# Gen oauth client id and client secret for github here
# https://github.com/settings/developers
OAUTH_CLIENT_SECRET = "some_id"
# ##############
# # SMTP/EMAIL #
# ##############
# username is offen same as seding email
smtp_username = "web@tftinker.tech"
smtp_password = "password"