# ##########
# # Server #
# ##########
# NOTE: non-root account only alows port grader then 1024
# Recomend: 8443 for ssl, 8080 for no ssl
port=8443
DOMAIN="sr.ewu.edu"
# #######
# # Log #
# #######
# TODO: log file
# TODO: log conifg
# #######
# # SSL #
# #######
# Free SSL https://letsencrypt.org/
SSL_ENABLE=true
SSL_CERTIFICATE="fullchain.pem"
SSL_KEY="privkey.pem"
#SSL_CERTIFICATE="/etc/letsencrypt/live/aws.tftinker.tech/fullchain.pem"
#SSL_KEY="/etc/letsencrypt/live/aws.tftinker.tech/privkey.pem"
# #########
# # Login #
# #########
# NOTE: github is free and easy to use as OAuth provider
OAUTH_CLIENT_ID = "client_id"
OAUTH_AUTH_URL = "https://example.com/login/oauth/authorize"
OAUTH_TOKEN_URL = "https://example.com/login/oauth/access_token"
# ##############
# # SMTP/EMAIL #
# ##############
# Who the email will be from
# (NOTE: need to have permissions to send emails from this in login)
smtp_email = "sr@ewu.edu"
# Email smtp entry point (STARTTLS ONLY)
# NOTE: EWU smtp email server is smtp.office365.com
smtp_server = "smtp.office365.com"
# Email for when there is errors
admin_email = "admin@ewu.edu"