port=8443
DOMAIN="aws.tftinker.tech"
# TODO: log file
SSL_ENABLE=true
SSL_CERTIFICATE="fullchain.pem"
SSL_KEY="privkey.pem"
#SSL_CERTIFICATE="/etc/letsencrypt/live/aws.tftinker.tech/fullchain.pem"
#SSL_KEY="/etc/letsencrypt/live/aws.tftinker.tech/privkey.pem"
# TODO: SMTP config
# TODO: DB config