name: Rust
# Mostly from: https://kerkour.com/rust-github-actions-ci-cd
# Also from: https://github.com/letsgetrusty/example_lib/blob/master/.github/workflows/rust.yml
on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.sh'
      - '**.yml'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  checks: write
  id-token: write

jobs:
  build_tests:

    runs-on: ubuntu-latest
    timeout-minutes: 40
    # NOTE already has rust
    # NOTE already has openssl

    steps:
      - uses: actions/checkout@v3

      # TODO: Does Cache work?
      # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      # https://github.com/marketplace/actions/cache
      - uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            studentpage/target/
            adminpage/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Takes around 8min's
      - name: Update local toolchain (takes around 8 mins)
        run: |
          rustup update
          rustup component add clippy
          rustup target add wasm32-unknown-unknown
          if ! command -v trunk &> /dev/null ; then cargo install --locked trunk; fi

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          trunk --version                 

      - name: Build
        run: |
          sh ./helper_scripts/build.sh

      - name: Build Code Doc
        run: |
          sh ./helper_scripts/build_code_doc.sh

      # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      # https://github.com/marketplace/actions/cache
      - uses: actions/cache/save@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            studentpage/target/
            adminpage/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: |
          cargo check --verbose
          cargo test --all --verbose

      - name: Lint warnings
        run: |
          sh ./helper_scripts/lint_warnings.sh

      - name: Lint No warnings
        run: |
          sh ./helper_scripts/lint.sh